var GAME_LEVELS = [   

  ["                           v           v                                 v      ",
   "                                                                                ",
   "                       o                                                        ",
   "                                                                                ",
   "                                                                                ",
   "                                               o                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                            o    o    o    o                  o                 ",
   "                         xxxxxxxxxxxxxxxxxxxxxx                                 ",
   "                                                                                ",
   "                                                                                ",
   "     @                                                                          ",
   "xxxxxxxxxxx                                                                     ",
   "                                                                                ",
   "                                                       x     -  x  o         o  ",
   "                                                       xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                   v                         v          v                                                ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",      
   "                                                                                              x   -  ox  ",
   "                                                                                     xxxxxxxxxxxxxxxxxx  ",
   "                                                                                     x                    ",
   "                                                                                     x                    ",
   "  @                                                                                  x                    ",
   "xxxxxxxxxxx                                                                          x                    ",
   "          x                                                                  x   -  ox                   ",
   "          x                                                             xxxxxxxxxxxxxx                   ",
   "          x                                                             x                                 ",
   "          x   -            x                                            x                                 ",
   "          xxxxxxxxxxxxxxxxxxx        xxx                                x                                 ",
   "                            x        x                                  x                                 ",
   "                            x        x                                  x                                 ",
   "                            x        x                          x   -  ox                                ",
   "                            x        x                xxxxxxxxxxxxxxxxxxx                                ",
   "                            x        x                x                                                   ",
   "                            xx      xx                x                                                   ",
   "                             xx o xxx                 x                                                   ",
   "                              x   x               xxxxx                                                  ",
   "                              x   x               x                                                      ",
   "                              x o                 x                                                      ",
   "                              x                   x                                                      ",
   "                              x o    -     -      x                                                      ",
   "                              xxxxxxxxxxxxxxxxxxxxx                                                      ",
   "                                                                                                         "],
   
     ["                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                        ",
   "                               x                                            x                                   ",
   "                               x o                                          x                                    ",
   "                               xxxxxxxx                         xxxxx       x                                        ",
   "                                      x                         xxxxx       x                                       ",
   "                                      x                         xxxxx v     x                                        ",
   "                                      x                         xxxxx       x                                        ",
   "                                      x                         xxxxx       x                                        ",
   "                                      xxx                       xxxxx       x                                        ",
   "                                      xv           o            xxxxx       x                                        ",
   "                 xx       xxxxxxxxxxxxx           xxxxx         xxxxx       x                                                      ",
   "                  xx     xxxxxxxxxxxxxx             v           xxxxx     v x                                            ",
   "                   xx   xxxxxxxxxxxxxxx                         xxxxx       x                                            ",
   "                    x o xxxxxxxxxxxxxxx                         xxxxx       x                                          ",
   "                    x   xxxxxxxxxxxxxxx                         xxxxx       x                                          ",
   " @                  x   xxxxxxxxxxxxxxx                         xxxxx       x                                          ",
   "xxxxx               x  oxxxxxxxxxxxxxxx                         xxxxx       x                                          ",
   "                    x   xxxxxxxxxxxxxxx                         xxxxx       x                                          ",
   "                    x   xxxxxxxxxxxxxxx                    o    xxxxx       x                                          ",
   "                    x   xxxxxxxxxxxxxxx                         xxxxx       x                                          ",
   "                    x   xxxxxxxxxxxxxxx                         xxxxx       x                                         ",
   "                    xo  xxxxxxxxxxxxxxx                         xxxxx       x                                                          ",
   "                    x   xxxooxxx                                xxxxx       x                                             ",
   "                    x   xxx  xxx      o                         xxxxx       x                                             ",
   "                    x   xxx  xxx  xxxxxxx          -            xxxxx       x                                                     ",
   "                    x   xxx  xxx  x     x       xxxxxxxx        xxxxx       x                                                        ",
   "                    x   xxx  xxx  x     x       x      x        xxxxx       x                                                  ",
   "                    x   xxx  xxx  x     x       x      x        xxxxx       x                                                  ",
   "                    x   xxx  xxx  x     x       x      x                    x                                             ",
   "                    x o xxx  xxx  x     x       x      x          o    -   ox                                             ",
   "                    x   xxx  xxx  x     x       x      xxxxxxxxxxxxxxxxxxxxxx                                                                ",
   "                    x   xxx  xxx  x     x       x                                                                       ",
   "                    x   xxx  xxx  x     x       x                                                                         ",
   "                    x             x     x       x                                                                   ",
   "                    x             x     x       x                                                                   ",
   "                    x  o   o     ox     x   -   x                                                                     ",
   "                    xxxxxxxxxxxxxxx     xxxxxxxxx                                                                          ",
   "                                                                                                              ",
   "                                                                                                              "],





  ["                                                        v                     v                                                                           v           v            v                                           xx                                                                  x                              ",
   "                              v                              v          v                                                                       v                            v               v                                xxx                                                                  x                             ",
   "                                             v                                        v                                                                         v                v                     v                     xxxx                                                                  x                               ",
   "                                         v                                                                                               v                                                                                  xxxxx                                            xxxxxxxxx             x                                     ",
   "                                                                     v          v                                                                                   v                    v                                 xxxxxx                                            xxxxxxxxx             x                                     ",
   "                                      v              v            v                                                                                       v                v                   v                          xxxxxxx                                            xxxxxxxxx        -    x                                            ",
   "                                                                v                                                                            v                                                            v    v         xxxxxxxx                                            xxxxxxxxx             x                                     ",
   "                                                                                                                                                    v                             v                                     xxxxxxxxx                                            xxxxxxxxx             x                                     ",
   "                                                                                                o                o                                                                                                     xxxxxxxxxx                                            xxxxxxxxx    -        x                                    ",                                 
   "                                                                                                                                                                                                                      xxxxxxxxxxx                                            xxxxxxxxx             x                                                     ",
   "                                                                                                                                                                                                                     xxxxxxxxxxxx                                            xxxxxxxxx             x                                       ",
   "                                                                                                                                                                                                                    xxxxxxxxxxxxx                                            xxxxxxxxx             x                                       ",
   "                                                                                                                                                                                                                   xxxxxxxxxxxxxx                                            xxxxxxxxx        -    x                                         ",
   "             xxxxxxxxxxxx  o                                                                                                                                                                                      xxxxxxxxxxxxxxx                        o      o      o     xxxxxxxxx             x                                       ",
   "                        xxxxx   o                                                                                                                                                                                xxxxxxxxxxxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             x                                                          ",
   "                            xxxxxx   o                                                                                                                                                                          xxxxxxxxxxxxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             x                                                           ",
   "                                 xxxxxx  o                                                                                                                                                                     xxxxxxxxxxxxxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      -      x                                                             ",
   "                                     xxxxxx         o        o                                                                                                                                                xxxxxxxxxxxxxxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             x                                                               ",
   "                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                   xxvxxvxxvxxvxxxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             x                                                        ",
   "                                                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                          xxx xx xx xx xxxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             x                                                                      ",
   "                                                                                                                                 xxxxxxxxxxxxxxxx                                                          xxxx xx xx xx xxxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             x                                                                                                  ",
   "                                                                                                                                                xxxxx                                                                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    -        x                                                                ",
   "                                                                                                                                                    xxxxx                                                                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             x                                                                   ",
   "                                                                                                                                                        xxxxxxxxxxxxxxxxxxxxx     o o o o o o o o o                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             x                                                                                          ",
   "                                                                                                                                                                            xxxxxxxxxxxxxxxxxxxxxxxxxxx  o                                 ooooo     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          o  x                                                                                             ",
   "                                                                                                                                                                                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                  ",
   "                                                                                                                                                                                                                                                                                                                                        ",
   "  @                                                                                                                                                                                                                                                                                                                                    ",
   "xxxxx                                                                                                                                                                                                                                                                                                                                    ",
   "                                                                                                                                                                                                                                                                                                                                        "]




];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
